---
name: Sourcery (for PR)

on:
  pull_request:

jobs:
  review-pr-with-sourcery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # https://github.com/sourcery-ai/action
      - uses: sourcery-ai/action@v1
        with:
          token: ${{ secrets.SOURCERY_TOKEN }}
          diff_ref: ${{ github.event.pull_request.base.sha }}
