---
name: Sourcery (for Codebase)

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  review-codebase-with-sourcery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # https://github.com/sourcery-ai/action
      - uses: sourcery-ai/action@v1
        with:
          token: ${{ secrets.SOURCERY_TOKEN }}
